### ISSUE TITLE
tscan regression bug with latest libfolia/frog?

### ISSUE THREAD

**Issue by proycon** [proycon/tscan#13]
T-scan won't run anymore after the latest update, I suspect a compatibility problem with the latest libfolia? I get:

```
frog-:Listening on port 7001
frog-:New connection...
Word(class='WORD',generate_id='tscan.p.1.s.1',set='tokconfig-default') creation failed: Set 'tokconfig-default' is used but has no declaration for token-annotation
```

**Comment by kosloot** [comment]
to be able to debug this, I need more information.
Does this happen with ALL text files in Tscan?  or just a specific example?

**Comment by proycon** [comment]
My own input is just plain text: "Dit is een test" , the input of the other users is probably different but my guess is it occurs with everything. Doesn't it reproduce? I pulled the error from the Frog server log.

**Comment by kosloot** [comment]
Not it doesn't reproduce.
When I locally run:
``frog -S 7001 --id=tscam --skip=mp -X``

and send via ``telnet localhost 7001``:
Dit is een test.
EOT

I get:
```xml
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="tscam" generator="libfolia-v2.4" version="2.2.1">
  <metadata type="native">
    <annotations>
      <token-annotation alias="tokconfig-nld" set="https://raw.githubusercontent.com/LanguageMachines/uctodata/master/setdefinitions/tokconfig-nld.foliaset.ttl">
        <annotator processor="ucto.1"/>
      </token-annotation>
      <paragraph-annotation>
        <annotator processor="ucto.1"/>
      </paragraph-annotation>
      <sentence-annotation>
        <annotator processor="ucto.1"/>
      </sentence-annotation>
      <quote-annotation>
        <annotator processor="ucto.1"/>
      </quote-annotation>
      <pos-annotation set="http://ilk.uvt.nl/folia/sets/frog-mbpos-cgn">
        <annotator processor="tagger.1"/>
      </pos-annotation>
      <lemma-annotation set="http://ilk.uvt.nl/folia/sets/frog-mblem-nl">
        <annotator processor="mblem.1"/>
      </lemma-annotation>
      <morphological-annotation set="http://ilk.uvt.nl/folia/sets/frog-mbma-nl">
        <annotator processor="mbma.1"/>
      </morphological-annotation>
      <chunking-annotation set="http://ilk.uvt.nl/folia/sets/frog-chunker-nl">
        <annotator processor="IOB.1"/>
      </chunking-annotation>
      <entity-annotation set="http://ilk.uvt.nl/folia/sets/frog-ner-nl">
        <annotator processor="NER.1"/>
      </entity-annotation>
      <text-annotation set="https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/text.foliaset.ttl"/>
    </annotations>
    <provenance>
      <processor xml:id="frog.1" begindatetime="2019-09-03T16:25:57" command="frog -S 7001 --id=tscam --skip=mp -X " folia_version="2.2.1" host="kokos" name="frog" user="sloot" version="0.19">
        <processor xml:id="frog.1.generator" folia_version="2.2.1" name="libfolia" type="generator" version="2.4"/>
        <processor xml:id="ucto.1" begindatetime="2019-09-03T16:25:57" name="ucto" version="0.19">
          <processor xml:id="uctodata.1" name="uctodata" type="datasource" version="0.8">
            <processor xml:id="uctodata.1.1" name="tokconfig-nld" type="datasource" version="0.2"/>
          </processor>
        </processor>
        <processor xml:id="tagger.1" begindatetime="2019-09-03T16:25:57" name="tagger" version="1.0"/>
        <processor xml:id="mblem.1" begindatetime="2019-09-03T16:25:57" name="mblem" version="1.2"/>
        <processor xml:id="mbma.1" begindatetime="2019-09-03T16:25:57" name="mbma" version="1.0"/>
        <processor xml:id="IOB.1" begindatetime="2019-09-03T16:25:57" name="IOB" version="2.0"/>
        <processor xml:id="NER.1" begindatetime="2019-09-03T16:25:57" name="NER" version="2.2"/>
      </processor>
    </provenance>
    <meta id="language">nld</meta>
  </metadata>
  <text xml:id="tscam.text">
    <p xml:id="tscam.p.1">
      <s xml:id="tscam.p.1.s.1">
        <w xml:id="tscam.p.1.s.1.w.1" class="WORD">
          <t>Dit</t>
          <pos class="VNW(aanw,pron,stan,vol,3o,ev)" confidence="0.777085" head="VNW">
            <feat class="aanw" subset="vwtype"/>
            <feat class="pron" subset="pdtype"/>
            <feat class="stan" subset="naamval"/>
            <feat class="vol" subset="status"/>
            <feat class="3o" subset="persoon"/>
            <feat class="ev" subset="getal"/>
          </pos>
          <lemma class="dit"/>
          <morphology>
            <morpheme>
              <t>dit</t>
            </morpheme>
          </morphology>
        </w>
        <w xml:id="tscam.p.1.s.1.w.2" class="WORD">
          <t>is</t>
          <pos class="WW(pv,tgw,ev)" confidence="0.999891" head="WW">
            <feat class="pv" subset="wvorm"/>
            <feat class="tgw" subset="pvtijd"/>
            <feat class="ev" subset="pvagr"/>
          </pos>
          <lemma class="zijn"/>
          <morphology>
            <morpheme>
              <t>zijn</t>
            </morpheme>
          </morphology>
        </w>
        <w xml:id="tscam.p.1.s.1.w.3" class="WORD">
          <t>een</t>
          <pos class="LID(onbep,stan,agr)" confidence="0.999113" head="LID">
            <feat class="onbep" subset="lwtype"/>
            <feat class="stan" subset="naamval"/>
            <feat class="agr" subset="npagr"/>
          </pos>
          <lemma class="een"/>
          <morphology>
            <morpheme>
              <t>een</t>
            </morpheme>
          </morphology>
        </w>
        <w xml:id="tscam.p.1.s.1.w.4" class="WORD" space="no">
          <t>test</t>
          <pos class="N(soort,ev,basis,zijd,stan)" confidence="0.903055" head="N">
            <feat class="soort" subset="ntype"/>
            <feat class="ev" subset="getal"/>
            <feat class="basis" subset="graad"/>
            <feat class="zijd" subset="genus"/>
            <feat class="stan" subset="naamval"/>
          </pos>
          <lemma class="test"/>
          <morphology>
            <morpheme>
              <t>test</t>
            </morpheme>
          </morphology>
        </w>
        <w xml:id="tscam.p.1.s.1.w.5" class="PUNCTUATION">
          <t>.</t>
          <pos class="LET()" confidence="1.000000" head="LET"/>
          <lemma class="."/>
          <morphology>
            <morpheme>
              <t>.</t>
            </morpheme>
          </morphology>
        </w>
        <chunking xml:id="tscam.p.1.s.1.chunking.1">
          <chunk xml:id="tscam.p.1.s.1.chunking.1.chunk.1" class="NP" confidence="1.000000">
            <wref id="tscam.p.1.s.1.w.1" t="Dit"/>
          </chunk>
          <chunk xml:id="tscam.p.1.s.1.chunking.1.chunk.2" class="VP" confidence="1.000000">
            <wref id="tscam.p.1.s.1.w.2" t="is"/>
          </chunk>
          <chunk xml:id="tscam.p.1.s.1.chunking.1.chunk.3" class="NP" confidence="1.000000">
            <wref id="tscam.p.1.s.1.w.3" t="een"/>
            <wref id="tscam.p.1.s.1.w.4" t="test"/>
          </chunk>
        </chunking>
      </s>
    </p>
  </text>
</FoLiA>
```

**Comment by proycon** [comment]
We reproduced it, it's caused by something in the old tscan frog configuration (separate from the frog default), which has been superseded in the latest git master but this has not been released yet!

**Comment by mhkuu** [comment]
So this would be resolved with a tag/release? :-)

**Comment by proycon** [comment]
We think/hope so yes

**Comment by mhkuu** [comment]
OK, released as v0.9.6, please re-open if this does not seem to solve things :-)

**Comment by proycon** [comment]
Ok, though this specific issue is solved (so keeping this issue closed), but the larger problem persists as there is another issue with Frog (LanguageMachines/Frog#81). The frog server doesn't return the proper response but closes the socket. The good news is that it only occurs in the latest stable Frog release the bug already seems fixed in the development release, so we'll have to do a new Frog release. It will be delayed for at least a week due to @kosloot 's holidays which started just now and he'll have to judge whether the other features he's been working on are ready for release already.

For the meantime a local workaround is to run LaMachine development.

**Comment by proycon** [comment]
(renamed and reopened this issue so we can better track it)

**Comment by kosloot** [comment]
I assume it can be fixed with just an ucto release. coming up soon

**Comment by kosloot** [comment]
[LanguageMachines/ucto] kosloot released v0.19 - https://github.com/LanguageMachines/ucto/releases/tag/v0.19

**Comment by proycon** [comment]
Doesn't seem to fix it yet unfortunately.

**Comment by kosloot** [comment]
ok, yes. I see.
A small frog update is also needed.

**Comment by proycon** [comment]
My own telnet test works now, so Frog returns proper output. But there's something wrong and something is segfaulting. I'm guessing tscan itself:

```
LanguageMachines/opened file input/test.txt
analyse tokenized sentence=Dit is een test
calling Alpino Server
calling Wopr
calling Wopr
done with Alpino Server
done with Wopr
done with Wopr
Segmentation fault
```

**Comment by proycon** [comment]
Reproduced with gdb backtrace: 

```
TScan 0.9.5
working dir /tmp/tscan-170078/
Information: multiple entry 'ok' in ADJ lex
Information: multiple entry 'almaar' in Intensify lex
skip line: nou al (expected 2 values, got 1)
skip line: nu al (expected 2 values, got 1)
skip line: nu reeds (expected 2 values, got 1)
Information: multiple entry 'buitencategorie' in Intensify lex
Information: multiple entry 'tering' in Intensify lex
Information: multiple entry 'visionair' in Intensify lex
Information: multiple entry 'variëteit' in general lex
read /var/www/lamachine2/weblamachine/src/tscan/data/freqlist_staphorsius_CLIB_words.freq (192912 entries)
read /var/www/lamachine2/weblamachine/src/tscan/data/SoNaR500.wordfreqlist_words.freq (478618654 entries)
read /var/www/lamachine2/weblamachine/src/tscan/data/SoNaR500.wordfreqlist_lemma.freq (432155270 entries)
opened file test.txt
analyse tokenized sentence=Dit is een test .
...
calling Alpino Server
calling Wopr
calling Wopr
done with Alpino Server
done with Wopr
done with Wopr

Thread 1 "tscan" received signal SIGSEGV, Segmentation fault.
get_compound_analysis[abi:cxx11](folia::Word*) (word=word@entry=0xe94c640) at FrogAPI.cxx:1791
1791            result.push_back( tag->feat( "compound" ) ); // might be empty
(gdb) bt
#0  get_compound_analysis[abi:cxx11](folia::Word*) (word=word@entry=0xe94c640) at FrogAPI.cxx:1791
#1  0x0000000000424d13 in wordStats::wordStats (this=0xe947040, index=<optimized out>, w=0xe94c640, alpWord=0x2aaac0005560, puncts=..., fail=<optimized out>)
    at tscan.cxx:1433
#2  0x00000000004268c4 in sentStats::sentStats (this=0xe92a7e0, index=<optimized out>, s=0xe94c3d0, pred=0x0) at tscan.cxx:1877
#3  0x0000000000428311 in parStats::parStats (this=0xe929410, index=<optimized out>, p=<optimized out>) at tscan.cxx:2620
#4  0x0000000000428abe in docStats::docStats (this=0x7fffffffcd10, doc=<optimized out>) at tscan.cxx:2710
#5  0x000000000040fe8e in main (argc=<optimized out>, argv=<optimized out>) at tscan.cxx:2990
```

**Comment by kosloot** [comment]
Ah,
I see. an incompatibility with the newest libfolia indeed.
Will release a bug fix later this day.

**Comment by proycon** [comment]
Confirmed! Issue solved now!

**Comment by pandermaat** [comment]
Wat fijn om dat te horen, Maarten en Ko! Bedankt alweer.

**Comment by proycon** [comment]
It seems the very same problem has occurred again, not sure yet why:

```
done with Alpino Server
done with Wopr
done with Wopr

Thread 1 "tscan" received signal SIGSEGV, Segmentation fault.
get_compound_analysis[abi:cxx11](folia::Word*) (word=word@entry=0xe94e640) at FrogAPI.cxx:1917
1917            result.push_back( tag->feat( "compound" ) ); // might be empty
(gdb) bt
#0  get_compound_analysis[abi:cxx11](folia::Word*) (word=word@entry=0xe94e640) at FrogAPI.cxx:1917
#1  0x0000000000424f03 in wordStats::wordStats (this=0xe934ba0, index=<optimized out>, w=0xe94e640, alpWord=0x2aaac8005540, puncts=..., fail=<optimized out>)
    at tscan.cxx:1433
#2  0x0000000000426ab4 in sentStats::sentStats (this=0xe92d680, index=<optimized out>, s=0xe94e3d0, pred=0x0) at tscan.cxx:1877
#3  0x0000000000428501 in parStats::parStats (this=0xe92c110, index=<optimized out>, p=<optimized out>) at tscan.cxx:2620
#4  0x0000000000428cae in docStats::docStats (this=0x7fffffffc8a0, doc=<optimized out>) at tscan.cxx:2710
#5  0x000000000041007e in main (argc=<optimized out>, argv=<optimized out>) at tscan.cxx:2990
```

```

**Comment by kosloot** [comment]
Hmmm,
this should have been fixed in Frog in september already. Not sure what happened there.
I patched Frog (again?)

**Comment by proycon** [comment]
For some reason it didn't end up in the v0.19 release I guess. Things failed again after a full LaMachine upgrade. Can we do a new Frog release with the fix?

**Comment by joepfranssen** [comment]
Thanks for looking into the problem. If I can help anyhow, let me know

**Comment by kosloot** [comment]
Well, the silly thing is, that frog carries some Tscan-only code. The problem popped up in that code.
A long overdue and unmentioned issue is, to move that code to T-scan.
it might be easy, but I have to look into it. 
For now, the fastest thing to do is a Frog bug fix release. Stay tuned...

**Comment by joepfranssen** [comment]
Thanks for the reply :) looking forward to it!  when are you planning on doing a frog bux fix release? I

**Comment by kosloot** [comment]
done

**Comment by proycon** [comment]
(I'll deploy it on the server, may take a few minutes)
